name: Build and Publish NuGet

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_ROLL_FORWARD: LatestMajor
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            6.0.x

      - name: Restore dependencies
        run: dotnet restore EDIFACT.sln

      - name: Build
        run: dotnet build EDIFACT.sln -c Release --no-restore

      - name: Test
        run: dotnet test Test/Edifact_Test.csproj -c Release --no-build --no-restore

      - name: Pack
        run: dotnet pack src/EDIFACT.csproj -c Release --no-build -o out

      - name: Upload package artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nuget-packages
          path: out/*.nupkg

      - name: Publish to NuGet
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push out/*.nupkg --source https://api.nuget.org/v3/index.json --api-key "$NUGET_API_KEY" --skip-duplicate
